### PR TITLE
Skipping dark mode + Minor changes to colors

### PR DESCRIPTION
**Pull request by Tushar-Naik**

### CODE REVIEW

**Comment by foufrix** [comment]
this PR is useful and avoids switching automatically to dark mode, just tested and it works well, can it be merged? So that we directly have it in the chrome store.
Thanks @Tushar-Naik 🙏

**Review by foufrix — APPROVED** [review]

**Review by abhisheksoni27 — APPROVED** [review]

**Comment by samueljim** [comment]
bump

**Comment by samueljim** [comment]
LGTM

**Comment by abhisheksoni27** [comment]
@callumlocke ?

**Comment by GovernmentPlates** [comment]
I really need this, it's so difficult to see the JSON on my computer's default dark theme. Pretty please? @callumlocke

**Review by tgomesfork — APPROVED** [review]

**Review by t-Ac3 — APPROVED** [review]

**Comment by kriskate** [comment]
it's really weird that the dark mode is not readable but disabling DM would do just fine

**Comment by callumlocke** [comment]
Thanks, same fix for forcing light mode #191 has been merged and submitted to store.

**Pull request closed without merging**
