### PR TITLE
Update to force light mode

### PR DESCRIPTION
**Pull request by beoss**
This should be a temporary work around for issue #190

### CODE REVIEW

**Review by assaf-itzikson — APPROVED** [review]
tested locally and it's working

**Review by ealcantara22 — APPROVED** [review]
looks good to me!

**Comment by gguillen** [comment]
Confirmed.  Working great on my end.

**Review by gguillen — APPROVED** [review]

**Comment by alex-nicholas** [comment]
Is there currently an expected release date for this? I use this extension almost daily when developing API's as its the quickest and easiest method to view json responses.

Keep up the good work!

**Comment by gguillen** [comment]
@alex-nicholas If you need it asap you can install it as an unpacked extension.  Follow the directions on the repo readme.

**Comment by callumlocke** [comment]
Thanks! I have submitted this to Chrome Web Store, it will be published when it passes review.

**Pull request merged**
